{% set name = "libusb" %}
{% set version = "1.0.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: 'https://github.com/libusb/libusb/releases/download/v{{ version}}/{{ name }}-{{ version }}.tar.bz2'
  sha256: 75aeb9d59a4fdb800d329a545c2e6799f732362193b465ea198f2aa275518157

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('libusb') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake  # [unix]
    - libtool  # [unix]

test:
  commands:
    - test -f $PREFIX/include/libusb-1.0/libusb.h  # [unix]
    - test -f $PREFIX/lib/libusb-1.0.a  # [unix]
    - test -f $PREFIX/lib/libusb-1.0${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\libusb-1.0.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libusb-1.0.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libusb-1.0.pdb exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libusb-1.0_static.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\libusb-1.0\\libusb.h exit 1  # [win]
    - conda inspect linkages -p $PREFIX libusb  # [not win]
    - conda inspect objects -p $PREFIX libusb  # [osx]

about:
  home: http://libusb.info/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'A cross-platform library to access USB devices'
  description: |
    libusb is a library for USB device access from Linux, Mac OS X, Windows,
    OpenBSD/NetBSD and Haiku userspace.
  doc_url: http://api.libusb.info/
  dev_url: https://github.com/libusb/libusb

extra:
  recipe-maintainers:
    - ryanvolz
