channels:
  targets:
  - [ryanvolz, main]
travis:
  secure:
    BINSTAR_TOKEN: gZKPkUcxXPWMloh3MJJa2QeMnYVEGpzA9bZ4QaO41R5Eh0GcUeCz05Zl9SSBXffLN+3LzdXl42Yx/F8GSvUcciAyfxbi4t9dgk83FFz8pTAI/0raTQgYKzxeIArlhdv+PpTZN7wA+8NcByXBXHCz2u/DNOPZvdAn8n8cwm53vYILP4yLqHk3d9/K0KQ1qBTfnGegnR5xCuv9AFh7YqbPVS3bA0iZeXu/ZwSDlKpZ1RWe0L039NneZgfLSLCTgp/cADyJy7B9amL66ASyhBRsANNEg0KMeL1MVmbfj2Ln3xELdFXa+4GSGbLjznxajdpE1av3V96ln+6VAtGnOHcrzAB3yXd47dHkhBs1uwOoUphCDZHGhDCeGpOZKlN5p2hOIU1k3wk1eY9T7YATcix2MVG7MqPqNb28zEc3zh6zJCT7MJTaReUprl8S3E2aXcbwR5MY+V1Ev4/76A21A3C10mAVl0tr4OdP40Es1unFfnwxFlr6fevTNxppk6VigydnlToQgx1sTpBtvgN0rTPaK6APOYmWcgEL9DGdHVGCuqp01cSgcN35+Lj0bmWvMlTqbYsOp99wiWWDuRAlI4UEXNqniiH8y06FN+WBxoj21+/UDFaDqY56tKKkvbTAtTywmnoDmLn3IgxKtIfqcBMPdj1loSE2usf10Gb2L2tDCfw=
appveyor:
  secure:
    BINSTAR_TOKEN: YRBUCxEtCawAWG6pOUMcpZRzCP9YYh4RCsm0JoqfUc48IikBjBYBNZJpTnszaSQw
